apiVersion: v1
kind: ConfigMap
metadata:
  name: admission-webhooks
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "portieris.name" . }}
    chart: {{ template "portieris.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  webhooks.yaml: |-
    {{- include "webhooks.yaml.tpl" . | indent 4}}
